{% set name = "ofxparse" %}
{% set version = "0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 057ab68d31270dece4d1a47662096aa76341968aaee145ffc711cb44cbd5c4a7

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - beautifulsoup4
    - lxml
    - python >={{ python_min }}
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - ofxparse

about:
  home: http://sites.google.com/site/ofxparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for working with the OFX (Open Financial Exchange) file format
  description: |
    ofxparse is a parser for Open Financial Exchange (.ofx) format files. OFX files are available from almost any online banking site, so they work well if you want to pull together your finances from multiple sources. Online trading accounts also provide account statements in OFX files.
  doc_url: https://github.com/jseutter/ofxparse/wiki
  dev_url: https://github.com/jseutter/ofxparse

extra:
  recipe-maintainers:
    - fdinel
